version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1
  aws-ecr: circleci/aws-ecr@9.0
  terraform: circleci/terraform@3.2
  node: circleci/node@5.1

jobs:
    release:
        executor: node/default
        steps:
        - checkout
        - node/install-packages # Install and automatically cache packages
        # Run optional required steps before releasing
        # - run: npm run build-script
        - run: npm run release
    build:
        machine:
            image: ubuntu-2204:2022.07.1
        parameters:
            version:
                default: "${CIRCLE_SHA1}"
                description: Image version
                type: string
        steps:
            - aws-ecr/build_and_push_image:
                auth:
                    - aws-cli/setup:
                        profile_name: default
                repo: "sample-js"
                tag: << parameters.version >>
                platform: linux/arm64
    deploy:
        executor: terraform/default
        parameters:
            version:
                default: "${CIRCLE_SHA1}"
                description: Image version
                type: string
        steps:
            - checkout
            - terraform/fmt:
                path: ./infrastructure
            - terraform/validate:
                path: ./infrastructure
            - terraform/init:
                path: ./infrastructure
                backend_config: "key=sample-js-tf,bucket=${AWS_BUCKET},region=${AWS_REGION}"
            - terraform/plan:
                path: ./infrastructure
            - terraform/apply:
                path: ./infrastructure
                var: "aws_account_id=${AWS_ACCOUNT_ID},aws_region=${AWS_REGION},image_name=sample-js,image_version=<< parameters.version >>"
    destroy:
        executor: terraform/default
        steps:
            - checkout
            - terraform/destroy:
                path: ./infrastructure
                backend_config: "key=sample-js-tf,bucket=${AWS_BUCKET},region=${AWS_REGION}"

workflows:
  release-wf:
    jobs:
      - release-approval:
          type: approval
          filters:
            branches:
              only: master
      - release:
          requires:
            - release-approval

  build-and-deploy:
    jobs:
      - build-and-deploy-approval:
          type: approval
      - build:
          version: "${CIRCLE_SHA1}"
          requires:
            - build-and-deploy-approval
      - deploy:
          version: "${CIRCLE_SHA1}"
          requires:
            - build

  build-and-deploy-when-release:
    jobs:
      - build:
          version: "${CIRCLE_TAG}"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - deploy:
          version: "${CIRCLE_TAG}"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
          requires:
            - build

  destroy-wf:
    jobs:
      - destroy-approval:
          type: approval
          filters:
            branches:
              only: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - destroy:
          requires:
            - destroy-approval
